import '@styles/globals.css';
import AppShell from '@components/AppShell'
import Footer from '@components/Footer'
import { bebas } from '@utils/fonts'

export const metadata = {
  title: "Santiagos Portfolio",
  description: 'Relentless Software Developer'
}

const Rootlayout = ({children,}:{children: React.ReactNode}) => {
  return (
    <html lang='en'>
      <body>
        <div className='main'>
        <main className='app'>
        {/* <video src = {require("../public/videos/backgroundVideo.mp4")} autoPlay loop muted /> */}
          <AppShell logoClassName={bebas.className}>
            {children}
          </AppShell>
        </main>
      <Footer/>
        </div>
      </body>
    </html>
  )
}

export default Rootlayout;



// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import './globals.css'
// // import Navbar from './api/Navbar'
// // import Footer from './api/Footer'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <>
//     {/* <Navbar/> */}
//     <main>{children}</main>
//     {/* <Footer/> */}
//     </>
//     // <html lang="en">
//     //   <body className={inter.className}>{children}</body>
//     // </html>
//   )
// }
