import '@styles/globals.css';
import AppShell from '@components/AppShell'
import Footer from '@components/Footer'
import { bebas } from '@utils/fonts'

export const metadata = {
  title: "Santiagos Portfolio",
  description: 'Relentless Software Developer'
}

const Rootlayout = ({children,}:{children: React.ReactNode}) => {
  const hydrationRescueScript =
    process.env.NODE_ENV === 'development'
      ? `(function(){
  window.addEventListener('load', function () {
    setTimeout(function () {
      var marker = document.querySelector('[data-hydrate-marker]');
      var hydrated = !!(marker && Object.keys(marker).some(function (k) {
        return k.indexOf('__reactFiber') === 0;
      }));
      if (hydrated) {
        try { sessionStorage.removeItem('dev-hydration-rescue'); } catch (e) {}
        return;
      }
      try {
        if (sessionStorage.getItem('dev-hydration-rescue') === '1') return;
        sessionStorage.setItem('dev-hydration-rescue', '1');
      } catch (e) { return; }
      location.reload();
    }, 1500);
  });
})();`
      : '';

  return (
    <html lang='en'>
      <body>
        {hydrationRescueScript ? (
          <script
            dangerouslySetInnerHTML={{
              __html: hydrationRescueScript,
            }}
          />
        ) : null}
        <div className='main'>
        <main className='app'>
          <AppShell logoClassName={bebas.className}>
            {children}
          </AppShell>
        </main>
      <Footer/>
        </div>
      </body>
    </html>
  )
}

export default Rootlayout;



// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import './globals.css'
// // import Navbar from './api/Navbar'
// // import Footer from './api/Footer'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <>
//     {/* <Navbar/> */}
//     <main>{children}</main>
//     {/* <Footer/> */}
//     </>
//     // <html lang="en">
//     //   <body className={inter.className}>{children}</body>
//     // </html>
//   )
// }
